name: telegram_image_cropper
description: "A flexible image cropping widget with InteractiveViewer, supporting web, desktop, and mobile."
version: 1.0.2
homepage: https://github.com/korotyshtatyana-cpu/image_cropper
repository: https://github.com/korotyshtatyana-cpu/image_cropper

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.9.1
  web: ^1.1.1
  vector_math: ^2.1.4

topics:
  - image-cropper
  - image-editor
  - flutter-widget
  - photo-editing

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0