name: image_cropper
description: "A flexible image cropping widget with InteractiveViewer, supporting web, desktop, and mobile."
version: 1.0.0
homepage: https://github.com/korotyshtatyana-cpu/image_cropper
repository: https://github.com/korotyshtatyana-cpu/image_cropper

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^3.0.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0